services:
  web:
    build: .
    image: cv-landing:latest
    volumes:
      - ./landing-page.conf:/etc/nginx/conf.d/landing-page.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets:/usr/share/nginx/html/assets:ro
    ports:
      - 80:80
    networks:
      - frontend

networks:
  frontend: {}